name: Scoring
on:
  push:
  schedule:
    # Every 30 mins between 11am to 7pm on 2/6 (JST)
    - cron: '0,30 2-10 6 2 *'
    # Every 30 mins between 10am to 7pm on 2/7 (JST)
    - cron: '0,30 1-8 7 2 *'
  workflow_dispatch:
env:
  PARALLEL_COUNT: 2
jobs:
  scoring:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetGroup: [0, 1]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn build
      - run: yarn scoring
        env:
          TARGET_GROUP: ${{ matrix.targetGroup }}
      - uses: shogo82148/actions-mutex@v1
      - name: Push scores
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add public
          git commit -m "Update scores"
          git push
  leaderboard:
    runs-on: ubuntu-latest
    needs:
      - scoring
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: yarn install
      - run: yarn build
      - run: yarn leaderboard
      - run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}
